name: Kaggle Data Download
on:
  workflow_call:
    secrets:
      KAGGLE_USERNAME:
        required: true
      KAGGLE_KEY:
        required: true

jobs:
  kaggle-download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Setup kaggle.json
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download data
        run: kaggle competitions download -c <competition-name> -p data/
