name: Run Jupyter Notebooks
on:
  workflow_call:
    secrets:
      KAGGLE_USERNAME:
        required: true
      KAGGLE_KEY:
        required: true

jobs:
  kaggle:
    uses: ./.github/workflows/kaggle.yml
    secrets:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      
  notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Get Data (Kaggle)
      uses: ./.github/workflows/kaggle.yml
    
    - name: Run Notebooks
      run: |
        for nb in notebooks/*.ipynb; do
          jupyter nbconvert --to notebook --execute "$nb" --stdout > /dev/null
        done
